#!/bin/bash

export ROOT_DIR=/app
export WDIR=/tmp/wdir
export VARIANT=lily3_12_2
export INSTANCE=instance1

cd $ROOT_DIR
make
rm -rf $VARIANT $WDIR

# Note: can be commented out after a first run
mkdir -p $VARIANT
./elisabeth buildPolynomialBasisMatrix $VARIANT

echo "[*] Generate the basis matrices"
./elisabeth buildBasisMatrices $VARIANT

echo "[*] Initialize an instance"
if [ ! -d $VARIANT/$INSTANCE ]; then
    mkdir -p $VARIANT/$INSTANCE
fi

if [ ! -f $VARIANT/$INSTANCE/key.dat ]; then
    ./elisabeth buildInstanceInit $VARIANT/$INSTANCE
fi

# Note: can be run for alternative key nibbles intervals [a:b] by changing "0 10".
echo "[*] Generate a system to solve"
JOBNAME=$(./elisabeth buildInstanceNext $VARIANT $VARIANT/$INSTANCE 0 10 | tee /dev/tty | grep -m 1 "Job" | sed -e 's/^Job \([^ ]*\) .*$/\1/')
#JOBNAME=$(./elisabeth buildInstanceNext $VARIANT $VARIANT/$INSTANCE 2 12 | tee /dev/tty | grep -m 1 "Job" | sed -e 's/^Job \([^ ]*\) .*$/\1/')

cd $VARIANT/$INSTANCE
# Aggregate the equations generated by parallel threads in buildInstanceNext
cat $JOBNAME-A-*.bin > $JOBNAME-A.bin
cd ../..
echo "[*] Finalizing generation of the system"
./elisabeth buildInstanceFinalize $VARIANT $VARIANT/$INSTANCE $JOBNAME


echo "[*] Block Wiedemann"
echo "  [*] Generate weight files"
cd $VARIANT/$INSTANCE && mf_scan2 $ROOT_DIR/$VARIANT/$INSTANCE/$JOBNAME-tA.bin
echo "  [*] Generate balancing data"
BALANCING=$(mf_bal                                         \
	2x2                                                    \
	mfile=$ROOT_DIR/$VARIANT/$INSTANCE/$JOBNAME-tA.bin     \
	reorder=columns                                        \
	rwfile=$ROOT_DIR/$VARIANT/$INSTANCE/$JOBNAME-tA.rw.bin \
	cwfile=$ROOT_DIR/$VARIANT/$INSTANCE/$JOBNAME-tA.cw.bin 2>&1 | tee /dev/tty | grep -m 1 "Writing balancing" | sed -e 's/^.*Writing balancing data to \([^ ]*\).*$/\1/')
echo "  [*] Compute solution"
mkdir -p $WDIR
bwc.pl :complete                             \
  wdir=$WDIR                                 \
  mn=64                                      \
  nullspace=left                             \
  matrix=$ROOT_DIR/$VARIANT/$INSTANCE/$JOBNAME-tA.bin \
  thr=2x2                                    \
  balancing=$BALANCING

echo "  [*] Retrieve the solution"
cp -L $WDIR/W $ROOT_DIR/$VARIANT/$INSTANCE/$JOBNAME-W
cd ../..
echo "[*] Extract key nibbles"
./elisabeth extractKey $VARIANT $VARIANT/$INSTANCE $JOBNAME
